//
//  GlyphCatalog.swift
//  RISE_RoutineTimer
//
//  The icons offered in the step editor.
//
//  Still curated rather than the whole Unicode emoji set: a routine step is a
//  shower, a stretch, a coffee or a page of notes, and a 1,900-item grid makes
//  those harder to find, not easier. But the first cut (about a hundred) was
//  too thin to cover a real morning — no socks, no dua, no numbers for a
//  sequence of steps — so it was grown to cover what routines actually hold.
//  Every entry carries search keywords, so "gym", "lift" and "weights" all
//  land on the same tile, and a routine's own vocabulary ("attar", "wudu",
//  "tongue scraper") finds something.
//
//  Rules for adding one:
//  - A single grapheme (no keycaps, flags or skin-tone sequences), or
//    `StepPaceTests.testEveryGlyphSurvivesNormalisation` fails.
//  - Not already in another category — `testGlyphsAreUnique`.
//  - Emoji 15.0 or older, so it renders on the iOS 17 deployment target.
//
//  Marks and Numbers are typographic rather than pictorial — they fit the
//  receipt/dot-matrix look better than colour emoji, for anyone who wants the
//  list to stay monochrome.
//

import Foundation

nonisolated struct Glyph: Identifiable, Equatable {
    let value: String
    let keywords: [String]

    var id: String { value }

    init(_ value: String, _ keywords: String...) {
        self.value = value
        self.keywords = keywords
    }

    func matches(_ query: String) -> Bool {
        let needle = query.lowercased()
        if value == query { return true }
        return keywords.contains { $0.contains(needle) }
    }
}

nonisolated struct GlyphCategory: Identifiable {
    let name: String
    let glyphs: [Glyph]

    var id: String { name }
}

nonisolated enum GlyphCatalog {
    static let categories: [GlyphCategory] = [
        GlyphCategory(name: "Morning", glyphs: [
            Glyph("☀️", "sun", "morning", "day", "sunrise", "light"),
            Glyph("🌅", "sunrise", "morning", "dawn", "sun", "fajr"),
            Glyph("🌄", "sunrise", "mountain", "morning", "dawn"),
            Glyph("🌤️", "sun", "cloud", "weather", "morning", "outside"),
            Glyph("🌙", "moon", "night", "evening", "sleep"),
            Glyph("⏰", "alarm", "clock", "wake", "time", "timer"),
            Glyph("🕰️", "clock", "time", "mantel", "schedule"),
            Glyph("⏳", "hourglass", "wait", "time", "timer", "patience"),
            Glyph("⌛", "hourglass", "done", "time", "timer"),
            Glyph("🔔", "bell", "reminder", "alert", "notify", "wake"),
            Glyph("🛏️", "bed", "sleep", "wake", "bedroom", "make bed"),
            Glyph("😴", "sleep", "tired", "nap", "rest"),
            Glyph("🥱", "yawn", "tired", "wake", "sleepy"),
            Glyph("☕", "coffee", "drink", "caffeine", "morning", "cup"),
            Glyph("🍵", "tea", "drink", "matcha", "green", "cup"),
            Glyph("💧", "water", "drink", "hydrate", "droplet"),
            Glyph("🥤", "drink", "shake", "smoothie", "cup", "water"),
            Glyph("🫗", "pour", "water", "drink", "glass", "hydrate"),
        ]),
        GlyphCategory(name: "Wash", glyphs: [
            Glyph("🚿", "shower", "wash", "bathe", "clean", "jump in"),
            Glyph("🛁", "bath", "bathe", "soak", "wash", "body wash"),
            Glyph("🪥", "toothbrush", "teeth", "brush", "dental", "wash", "floss"),
            Glyph("🧼", "soap", "wash", "clean", "hands", "face wash"),
            Glyph("🫧", "bubbles", "mouthwash", "rinse", "foam", "clean", "wudu"),
            Glyph("🧴", "lotion", "skincare", "moisturise", "moisturize", "cream", "shampoo", "deodorant", "attar", "perfume", "cologne"),
            Glyph("🧽", "sponge", "scrub", "wash", "clean", "exfoliate"),
            Glyph("🪒", "shave", "razor", "groom", "beard"),
            Glyph("💈", "barber", "haircut", "groom", "hair"),
            Glyph("💇", "hair", "haircut", "style", "groom"),
            Glyph("🪮", "comb", "hair", "groom", "brush", "style"),
            Glyph("🪞", "mirror", "groom", "check", "skincare", "look"),
            Glyph("🧖", "towel", "steam", "sauna", "spa", "relax"),
            Glyph("💅", "nails", "manicure", "groom", "polish"),
            Glyph("👅", "tongue", "tongue scraper", "mouth", "oral"),
            Glyph("🦷", "teeth", "tooth", "dental", "brush", "mouthwash", "floss"),
            Glyph("👃", "nose", "smell", "breathe", "nasal"),
            Glyph("👁️", "eye", "eyes", "drops", "contacts", "look"),
            Glyph("🧻", "paper", "bathroom", "toilet", "roll"),
            Glyph("🚽", "toilet", "bathroom", "restroom", "loo"),
            Glyph("💊", "pill", "medicine", "vitamin", "supplement"),
            Glyph("🩹", "bandage", "plaster", "first aid", "skin"),
            Glyph("🌡️", "thermometer", "temperature", "health", "check"),
            Glyph("🩺", "stethoscope", "health", "doctor", "check"),
        ]),
        GlyphCategory(name: "Dress", glyphs: [
            Glyph("👔", "dress", "clothes", "shirt", "getready", "outfit", "tie"),
            Glyph("👕", "tshirt", "shirt", "clothes", "top", "getting dressed"),
            Glyph("👖", "jeans", "trousers", "pants", "clothes"),
            Glyph("🩲", "boxers", "underwear", "briefs", "clothes"),
            Glyph("🩳", "shorts", "clothes", "gym", "summer"),
            Glyph("🧦", "socks", "clothes", "feet", "getting dressed"),
            Glyph("👗", "dress", "clothes", "outfit"),
            Glyph("🧥", "coat", "jacket", "outerwear", "leave"),
            Glyph("🥼", "lab coat", "coat", "work", "uniform"),
            Glyph("🦺", "vest", "safety", "hi vis", "uniform", "work"),
            Glyph("🧕", "hijab", "headscarf", "modest", "dress"),
            Glyph("👟", "shoes", "trainers", "sneakers", "getready", "run"),
            Glyph("👞", "shoes", "formal", "loafers", "dress"),
            Glyph("🥾", "boots", "hiking", "shoes", "outdoor"),
            Glyph("👠", "heels", "shoes", "dress"),
            Glyph("🧢", "cap", "hat", "baseball"),
            Glyph("🎩", "hat", "top hat", "formal"),
            Glyph("🧣", "scarf", "winter", "warm"),
            Glyph("🧤", "gloves", "winter", "warm"),
            Glyph("👓", "glasses", "spectacles", "eyes", "read"),
            Glyph("🕶️", "sunglasses", "shades", "outside"),
            Glyph("⌚", "watch", "time", "wrist", "accessories"),
            Glyph("💍", "ring", "jewelry", "jewellery", "chain", "necklace", "accessories"),
            Glyph("👜", "handbag", "bag", "purse"),
            Glyph("🎒", "bag", "pack", "backpack", "getready", "school"),
        ]),
        GlyphCategory(name: "Body", glyphs: [
            Glyph("🧘", "stretch", "yoga", "meditate", "calm", "breathe"),
            Glyph("🤸", "stretch", "exercise", "mobility", "cartwheel", "workout"),
            Glyph("🏃", "run", "jog", "cardio", "exercise", "running"),
            Glyph("🚶", "walk", "steps", "stroll", "exercise"),
            Glyph("🏋️", "gym", "lift", "weights", "strength", "workout"),
            Glyph("💪", "strength", "muscle", "gym", "workout", "lift", "pushups"),
            Glyph("🚴", "bike", "cycle", "cycling", "cardio", "exercise"),
            Glyph("🏊", "swim", "pool", "cardio", "exercise"),
            Glyph("🧗", "climb", "bouldering", "exercise"),
            Glyph("🥊", "boxing", "punch", "workout", "fight"),
            Glyph("🥋", "martial arts", "karate", "judo", "bjj"),
            Glyph("🤾", "handball", "sport", "exercise"),
            Glyph("⛹️", "basketball", "sport", "exercise"),
            Glyph("🏀", "basketball", "ball", "sport"),
            Glyph("⚽", "football", "soccer", "ball", "sport"),
            Glyph("🎾", "tennis", "ball", "sport"),
            Glyph("🏓", "table tennis", "ping pong", "sport"),
            Glyph("🏸", "badminton", "sport"),
            Glyph("🏌️", "golf", "sport"),
            Glyph("🏄", "surf", "sport", "water"),
            Glyph("⛷️", "ski", "snow", "sport"),
            Glyph("🛹", "skateboard", "skate", "sport"),
            Glyph("🩰", "ballet", "dance", "stretch"),
            Glyph("🦵", "leg", "legs", "squat", "stretch", "mobility"),
            Glyph("🦶", "foot", "feet", "stretch", "massage"),
            Glyph("❤️", "heart", "health", "cardio", "love"),
            Glyph("🫀", "heart", "cardio", "health", "pulse"),
            Glyph("🫁", "lungs", "breathe", "breath", "breathing"),
        ]),
        GlyphCategory(name: "Food", glyphs: [
            Glyph("🍳", "breakfast", "egg", "cook", "food", "eat", "meal"),
            Glyph("🥣", "cereal", "breakfast", "bowl", "food", "eat", "oats"),
            Glyph("🥗", "salad", "food", "eat", "healthy", "meal", "lunch"),
            Glyph("🍎", "apple", "fruit", "food", "eat", "snack"),
            Glyph("🍌", "banana", "fruit", "snack"),
            Glyph("🍊", "orange", "fruit", "juice", "snack"),
            Glyph("🍓", "strawberry", "fruit", "berries"),
            Glyph("🫐", "blueberries", "fruit", "berries", "smoothie"),
            Glyph("🍇", "grapes", "fruit", "snack"),
            Glyph("🥑", "avocado", "toast", "healthy"),
            Glyph("🍯", "honey", "sweet", "tea"),
            Glyph("🥚", "egg", "boil", "protein", "breakfast"),
            Glyph("🥓", "bacon", "breakfast", "protein"),
            Glyph("🧀", "cheese", "snack", "dairy"),
            Glyph("🥞", "pancakes", "breakfast", "sweet"),
            Glyph("🧇", "waffle", "breakfast", "sweet"),
            Glyph("🥯", "bagel", "breakfast", "bread"),
            Glyph("🍞", "bread", "toast", "breakfast"),
            Glyph("🥐", "croissant", "pastry", "breakfast"),
            Glyph("🥜", "nuts", "peanuts", "snack", "protein"),
            Glyph("🍚", "rice", "meal", "lunch", "dinner"),
            Glyph("🍲", "stew", "soup", "meal", "cook"),
            Glyph("🥪", "sandwich", "lunch", "packed lunch", "meal prep"),
            Glyph("🍱", "bento", "lunchbox", "meal prep", "lunch"),
            Glyph("🥛", "milk", "dairy", "drink", "protein"),
            Glyph("🧃", "juice", "drink", "box"),
            Glyph("🧋", "boba", "bubble tea", "drink"),
            Glyph("🫖", "teapot", "tea", "brew", "chai"),
            Glyph("🧊", "ice", "cold", "plunge", "water"),
            Glyph("🍫", "chocolate", "treat", "sweet"),
        ]),
        GlyphCategory(name: "Faith", glyphs: [
            Glyph("🤲", "dua", "supplication", "pray", "prayer", "hands", "ask"),
            Glyph("🙏", "pray", "prayer", "gratitude", "thanks", "shukr", "meditate"),
            Glyph("📿", "prayer", "beads", "tasbeeh", "tasbih", "dhikr", "rosary", "misbaha"),
            Glyph("🕌", "mosque", "prayer", "salah", "namaz", "masjid", "worship"),
            Glyph("🕋", "kaaba", "mecca", "qibla", "salah", "hajj"),
            Glyph("☪️", "islam", "crescent", "faith", "muslim"),
            Glyph("🛐", "worship", "pray", "place of worship", "salah"),
            Glyph("🧎", "kneel", "sujood", "prayer", "worship"),
            Glyph("🕯️", "candle", "light", "reflect", "calm"),
            Glyph("✨", "sparkle", "niyyah", "intention", "blessing", "new"),
            Glyph("🫶", "heart hands", "gratitude", "love", "thanks"),
            Glyph("☮️", "peace", "calm", "harmony"),
            Glyph("⛪", "church", "prayer", "worship"),
            Glyph("✝️", "cross", "christian", "faith", "prayer"),
            Glyph("🕍", "synagogue", "prayer", "worship"),
            Glyph("✡️", "star of david", "jewish", "faith"),
            Glyph("🕉️", "om", "hindu", "meditate", "faith"),
            Glyph("☸️", "dharma", "buddhist", "wheel", "faith"),
        ]),
        GlyphCategory(name: "Mind", glyphs: [
            Glyph("📝", "notes", "write", "journal", "plan", "todo"),
            Glyph("✍️", "write", "journal", "notes", "handwriting"),
            Glyph("📓", "notebook", "journal", "write", "diary"),
            Glyph("📔", "journal", "diary", "notebook", "gratitude"),
            Glyph("🗒️", "notepad", "notes", "list", "plan", "todo"),
            Glyph("📖", "read", "book", "reading", "study", "quran"),
            Glyph("📚", "books", "read", "study", "learn"),
            Glyph("🧠", "brain", "mind", "think", "focus", "learn"),
            Glyph("💭", "think", "thought", "reflect", "mind"),
            Glyph("💡", "idea", "lightbulb", "think", "insight"),
            Glyph("🎯", "goal", "target", "focus", "aim", "intention"),
            Glyph("🧩", "puzzle", "problem", "think", "focus"),
            Glyph("♟️", "chess", "strategy", "think", "game"),
            Glyph("🧮", "abacus", "maths", "math", "count"),
            Glyph("🎧", "headphones", "music", "listen", "podcast", "audio"),
            Glyph("🎵", "music", "song", "listen", "audio"),
            Glyph("🎹", "piano", "keyboard", "music", "practice"),
            Glyph("🎸", "guitar", "music", "practice"),
            Glyph("🎙️", "microphone", "podcast", "record", "voice"),
            Glyph("🗣️", "speak", "practice", "language", "affirmation"),
            Glyph("🎨", "art", "paint", "draw", "create"),
            Glyph("🌐", "language", "world", "learn", "news", "internet"),
            Glyph("🔕", "silence", "quiet", "do not disturb", "focus"),
            Glyph("📵", "no phone", "screen free", "offline", "focus"),
            Glyph("😌", "calm", "relax", "content", "breathe"),
            Glyph("😊", "smile", "happy", "mood", "check in"),
        ]),
        GlyphCategory(name: "Work", glyphs: [
            Glyph("💻", "laptop", "work", "computer", "code", "desk"),
            Glyph("⌨️", "keyboard", "type", "work", "code"),
            Glyph("🖥️", "desktop", "computer", "work", "monitor", "screen"),
            Glyph("💼", "briefcase", "work", "office", "job"),
            Glyph("📊", "chart", "data", "report", "work", "review", "stats"),
            Glyph("📈", "growth", "chart", "progress", "up", "review", "stats"),
            Glyph("📅", "calendar", "schedule", "plan", "day", "agenda"),
            Glyph("🗓️", "calendar", "week", "plan", "schedule"),
            Glyph("📋", "clipboard", "checklist", "list", "plan"),
            Glyph("✅", "done", "check", "complete", "task", "todo"),
            Glyph("📌", "pin", "important", "note", "task"),
            Glyph("📎", "paperclip", "attach", "admin"),
            Glyph("🗂️", "files", "organise", "organize", "folder", "admin"),
            Glyph("🗄️", "filing", "cabinet", "archive", "admin"),
            Glyph("📧", "email", "inbox", "mail", "message"),
            Glyph("✉️", "letter", "mail", "post", "message"),
            Glyph("📞", "call", "phone", "ring", "meeting"),
            Glyph("📱", "phone", "mobile", "screen", "device"),
            Glyph("🔋", "battery", "charge", "power", "energy"),
            Glyph("⚙️", "settings", "setup", "config", "admin", "gear"),
            Glyph("💰", "money", "finance", "budget", "cash"),
            Glyph("💳", "card", "pay", "bills", "finance"),
            Glyph("🧾", "receipt", "expenses", "bills", "finance"),
            Glyph("📦", "package", "parcel", "delivery", "post"),
            Glyph("🖨️", "print", "printer", "documents"),
        ]),
        GlyphCategory(name: "Home", glyphs: [
            Glyph("🏠", "home", "house", "tidy"),
            Glyph("🚪", "door", "leave", "lock up", "exit"),
            Glyph("🪟", "window", "open", "air", "blinds", "light"),
            Glyph("🛋️", "couch", "sofa", "living room", "relax"),
            Glyph("🪑", "chair", "desk", "sit", "posture"),
            Glyph("🧹", "sweep", "clean", "tidy", "broom", "chores"),
            Glyph("🧺", "laundry", "washing", "clothes", "chores", "basket", "fold clothes"),
            Glyph("🪣", "bucket", "mop", "clean", "chores"),
            Glyph("🍽️", "dishes", "wash", "kitchen", "chores", "plate", "eat"),
            Glyph("🗑️", "bin", "trash", "rubbish", "chores", "waste"),
            Glyph("🛒", "shopping", "groceries", "store", "errand"),
            Glyph("🧰", "toolbox", "fix", "repair", "diy"),
            Glyph("🔧", "wrench", "fix", "repair", "maintenance"),
            Glyph("🔌", "plug", "charge", "unplug", "power"),
            Glyph("🔑", "keys", "lock", "leave", "getready"),
            Glyph("🪴", "plant", "water", "garden", "houseplant"),
            Glyph("🐕", "dog", "walk", "pet", "animal"),
            Glyph("🐈", "cat", "pet", "feed", "animal"),
            Glyph("🐟", "fish", "feed", "pet", "tank"),
            Glyph("🐦", "bird", "feed", "pet"),
            Glyph("👶", "baby", "kids", "child", "family"),
            Glyph("🍼", "bottle", "baby", "feed", "family"),
            Glyph("🧸", "teddy", "kids", "toys", "tidy"),
        ]),
        GlyphCategory(name: "Out", glyphs: [
            Glyph("🚗", "car", "drive", "commute", "leave", "travel"),
            Glyph("🚌", "bus", "commute", "transit", "travel"),
            Glyph("🚇", "metro", "subway", "train", "commute"),
            Glyph("🚆", "train", "rail", "commute", "travel"),
            Glyph("🚲", "bicycle", "bike", "commute", "ride"),
            Glyph("🛴", "scooter", "commute", "ride"),
            Glyph("✈️", "flight", "plane", "travel", "airport"),
            Glyph("⛽", "fuel", "petrol", "gas", "car"),
            Glyph("🏫", "school", "drop off", "kids", "class"),
            Glyph("🏢", "office", "work", "building", "commute"),
            Glyph("🏥", "hospital", "doctor", "appointment", "health"),
            Glyph("🏪", "shop", "store", "errand", "convenience"),
            Glyph("📍", "location", "place", "destination", "pin"),
            Glyph("🧭", "compass", "direction", "navigate", "plan"),
            Glyph("🗺️", "map", "route", "plan", "travel"),
            Glyph("☂️", "umbrella", "rain", "weather", "leave"),
        ]),
        GlyphCategory(name: "Nature", glyphs: [
            Glyph("🌱", "seedling", "grow", "new", "habit", "garden"),
            Glyph("🌳", "tree", "park", "outside", "nature"),
            Glyph("🌲", "pine", "forest", "outside", "nature"),
            Glyph("🍃", "leaves", "breeze", "fresh", "air"),
            Glyph("🍂", "autumn", "fall", "leaves", "season"),
            Glyph("🌸", "blossom", "flower", "spring", "fragrance"),
            Glyph("🌻", "sunflower", "flower", "sunny", "happy"),
            Glyph("🌷", "tulip", "flower", "spring"),
            Glyph("🌊", "wave", "ocean", "sea", "cold", "swim"),
            Glyph("⛰️", "mountain", "hike", "outside", "climb"),
            Glyph("🔥", "fire", "streak", "energy", "hot", "motivation"),
            Glyph("⚡", "lightning", "energy", "power", "fast"),
            Glyph("❄️", "snow", "cold", "winter", "ice bath"),
            Glyph("☁️", "cloud", "weather", "sky"),
            Glyph("🌧️", "rain", "weather", "umbrella"),
            Glyph("🌈", "rainbow", "weather", "hope"),
            Glyph("⭐", "star", "favourite", "favorite", "goal"),
            Glyph("🌟", "glowing star", "win", "best", "shine"),
            Glyph("🪐", "planet", "space", "big picture"),
            Glyph("🐚", "shell", "beach", "calm"),
        ]),
        GlyphCategory(name: "Colour", glyphs: [
            Glyph("🔴", "red", "circle", "colour", "color"),
            Glyph("🟠", "orange", "circle", "colour", "color"),
            Glyph("🟡", "yellow", "circle", "colour", "color"),
            Glyph("🟢", "green", "circle", "colour", "color"),
            Glyph("🔵", "blue", "circle", "colour", "color"),
            Glyph("🟣", "purple", "circle", "colour", "color"),
            Glyph("🟤", "brown", "circle", "colour", "color"),
            Glyph("⚫", "black", "circle", "colour", "color"),
            Glyph("⚪", "white", "circle", "colour", "color"),
            Glyph("🟥", "red", "square", "colour", "color"),
            Glyph("🟧", "orange", "square", "colour", "color"),
            Glyph("🟨", "yellow", "square", "colour", "color"),
            Glyph("🟩", "green", "square", "colour", "color"),
            Glyph("🟦", "blue", "square", "colour", "color"),
            Glyph("🟪", "purple", "square", "colour", "color"),
            Glyph("🟫", "brown", "square", "colour", "color"),
            Glyph("⬛", "black", "square", "colour", "color"),
            Glyph("⬜", "white", "square", "colour", "color"),
            Glyph("🧡", "orange", "heart", "love"),
            Glyph("💛", "yellow", "heart", "love"),
            Glyph("💚", "green", "heart", "love"),
            Glyph("💙", "blue", "heart", "love"),
            Glyph("💜", "purple", "heart", "love"),
            Glyph("🖤", "black", "heart", "love"),
            Glyph("🤍", "white", "heart", "love", "pure"),
            Glyph("🤎", "brown", "heart", "love"),
            Glyph("🩷", "pink", "heart", "love"),
            Glyph("🩵", "light blue", "heart", "love"),
            Glyph("🩶", "grey", "gray", "heart", "love"),
        ]),
        GlyphCategory(name: "Numbers", glyphs: [
            Glyph("1", "one", "number", "first", "step"),
            Glyph("2", "two", "number", "second", "step"),
            Glyph("3", "three", "number", "third", "step"),
            Glyph("4", "four", "number", "fourth", "step"),
            Glyph("5", "five", "number", "fifth", "step"),
            Glyph("6", "six", "number", "step"),
            Glyph("7", "seven", "number", "step"),
            Glyph("8", "eight", "number", "step"),
            Glyph("9", "nine", "number", "step"),
            Glyph("0", "zero", "number", "step"),
            Glyph("①", "one", "number", "circled", "first"),
            Glyph("②", "two", "number", "circled", "second"),
            Glyph("③", "three", "number", "circled", "third"),
            Glyph("④", "four", "number", "circled"),
            Glyph("⑤", "five", "number", "circled"),
            Glyph("⑥", "six", "number", "circled"),
            Glyph("⑦", "seven", "number", "circled"),
            Glyph("⑧", "eight", "number", "circled"),
            Glyph("⑨", "nine", "number", "circled"),
            Glyph("⑩", "ten", "number", "circled"),
            Glyph("❶", "one", "number", "filled", "first"),
            Glyph("❷", "two", "number", "filled", "second"),
            Glyph("❸", "three", "number", "filled", "third"),
            Glyph("❹", "four", "number", "filled"),
            Glyph("❺", "five", "number", "filled"),
            Glyph("❻", "six", "number", "filled"),
            Glyph("❼", "seven", "number", "filled"),
            Glyph("❽", "eight", "number", "filled"),
            Glyph("❾", "nine", "number", "filled"),
            Glyph("❿", "ten", "number", "filled"),
        ]),
        GlyphCategory(name: "Marks", glyphs: [
            Glyph("★", "star", "favourite", "favorite", "mark"),
            Glyph("☆", "star", "outline", "mark"),
            Glyph("✦", "sparkle", "star", "four point", "mark"),
            Glyph("✧", "sparkle", "star", "outline", "mark"),
            Glyph("✱", "asterisk", "star", "mark"),
            Glyph("❋", "flower", "asterisk", "ornament", "mark"),
            Glyph("●", "dot", "circle", "filled", "bullet"),
            Glyph("○", "circle", "outline", "ring"),
            Glyph("◉", "target", "circle", "bullseye", "focus"),
            Glyph("◎", "circle", "double", "ring", "target"),
            Glyph("◐", "half", "circle", "halfway", "moon"),
            Glyph("◑", "half", "circle", "halfway", "moon"),
            Glyph("◆", "diamond", "filled"),
            Glyph("◇", "diamond", "outline"),
            Glyph("❖", "diamond", "ornament", "mark"),
            Glyph("■", "square", "filled", "block"),
            Glyph("□", "square", "outline", "box"),
            Glyph("▣", "square", "inset", "box", "checkbox"),
            Glyph("▦", "grid", "square", "pattern"),
            Glyph("⬢", "hexagon", "filled", "shape"),
            Glyph("⬡", "hexagon", "outline", "shape"),
            Glyph("▲", "triangle", "up", "arrow"),
            Glyph("▶", "play", "start", "triangle", "right"),
            Glyph("➤", "arrow", "next", "right", "go"),
            Glyph("↻", "repeat", "again", "cycle", "refresh"),
            Glyph("⇥", "next", "tab", "skip", "forward"),
            Glyph("✓", "check", "tick", "done", "complete"),
            Glyph("✕", "cross", "close", "no", "cancel"),
            Glyph("✚", "plus", "add", "cross", "health"),
            Glyph("∞", "infinity", "forever", "habit", "loop"),
            Glyph("≈", "approximately", "about", "wave"),
            Glyph("♪", "note", "music", "song"),
            Glyph("♫", "notes", "music", "song"),
            Glyph("♥", "heart", "love", "suit"),
            Glyph("☼", "sun", "light", "outline"),
            Glyph("☾", "moon", "night", "crescent", "outline"),
            Glyph("⌂", "home", "house", "outline"),
            Glyph("§", "section", "text", "paragraph"),
            Glyph("†", "dagger", "mark"),
            Glyph("°", "degree", "temperature", "heat"),
            Glyph("※", "reference", "note", "mark"),
            Glyph("⌘", "command", "key", "control"),
            Glyph("⚑", "flag", "goal", "target", "milestone"),
            Glyph("☰", "menu", "lines", "list", "bars"),
        ]),
    ]

    /// Categories filtered by a search query, empty ones dropped.
    static func filtered(by query: String) -> [GlyphCategory] {
        let trimmed = query.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return categories }
        return categories.compactMap { category in
            let hits = category.glyphs.filter { $0.matches(trimmed) }
            return hits.isEmpty ? nil : GlyphCategory(name: category.name, glyphs: hits)
        }
    }
}
